"""empty message

Revision ID: 0b1377c3bab5
Revises: 8ae29d8eb47a
Create Date: 2025-04-14 19:15:12.708166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1377c3bab5'
down_revision: Union[str, None] = '8ae29d8eb47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='events', 
        column_name='type', 
        new_column_name='event_type'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='events', 
        column_name='event_type', 
        new_column_name='type'
        )
    # ### end Alembic commands ###
