"""empty message

Revision ID: 71cf717d0d77
Revises: 00e580101503
Create Date: 2025-03-27 08:48:23.345137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71cf717d0d77'
down_revision: Union[str, None] = '00e580101503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('courier', 'couriers')
    op.rename_table('order', 'orders')
    op.alter_column('transport',
        sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'])
        )
    op.rename_table('transport', 'transports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('couriers', 'courier')
    op.rename_table('orders', 'order')
    op.alter_column('transports',
        sa.ForeignKeyConstraint(['courier_id'], ['courier.id'])
        )
    op.rename_table('transports', 'transport')
    # ### end Alembic commands ###
