services:

  delivery:
    build:
      context: .
    volumes:
      - ./:/app/
    env_file:
      - .env
    restart: always
    container_name: delivery
    command: "poetry run python api/adapters/http/contract/src/openapi_server/main.py"
    ports:
      - 8888:8000
    depends_on:
      - db

  consumer:
    build:
      context: .
    volumes:
      - ./:/app/
    env_file:
      - .env
    restart: always
    container_name: delivery_consumer
    command: "poetry run python api/adapters/kafka/main.py"
    depends_on:
      - db

  scheduler:
    build:
      context: .
    volumes:
      - ./:/app/
    env_file:
      - .env
    restart: always
    container_name: delivery_scheduler
    command: "poetry run python api/adapters/scheduler/main.py"
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine3.20
    platform: linux/amd64
    env_file:
      - .env
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

volumes:
  db_data: