[project]
name = "delivery"
version = "0.1.0"
description = ""
authors = [
    {name = "NEPOCHATYKH Dmitry A",email = "dmitry.nepochatykh@raiffeisen.ru"}
]
readme = "README.md"
requires-python = ">=3.12,<4"
dependencies = [
    "fastapi (>=0.115.11,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "sqlalchemy (>=2.0.38,<3.0.0)",
    "pydantic-settings (>=2.8.1,<3.0.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "grpcio (>=1.70.0,<2.0.0)",
    "grpcio-tools (>=1.70.0,<2.0.0)",
    "that-depends (>=2.2.0,<3.0.0)",
    "alembic (>=1.15.1,<2.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "greenlet (>=3.1.1,<4.0.0)"
]

[tool.poetry]
packages = [
    { include= "api" },
    { include= "core" },
    { include= "infrastructure" },
    { include= "tests" },
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[tool.pytest.ini_options]
minversion = "8.3"
addopts = " -v "
python_classes = [
    "*Should"
]
python_files = [
    "*_tests.py"
]
python_functions = [
    "be_*",
    "not_be_*",
]
testpaths = [
    "tests"
]
